apiVersion: apps/v1
kind: Deployment
metadata:
  name: aj-simple-autos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aj-simple-autos
  template:
    metadata:
      labels:
        app: aj-simple-autos
    spec:
      containers:
        - image: registry.gitlab.com/galv-vmw-apr-2021/2-simple-autos/aj-angie:latest
          name: aj-simple-autos
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value:
            - name: DB_NAME
              value:
            - name: DB_USER
              value:
            - name: DB_PWD
              value:
      imagePullSecrets: # Be sure the token name matches what you created on K8s
        - name: deploy