apiVersion: apps/v1
kind: Deployment
metadata:
  name: aj-simple-autos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aj-simple-autos
  template:
    metadata:
      labels:
        app: aj-simple-autos
    spec:
      containers:
        - image: registry.gitlab.com/ajbenjumea/aj-angie:latest
          name: aj-simple-autos
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "$DB_HOST"
            - name: DB_NAME
              value: "$DB_NAME"
            - name: DB_USER
              value: "$DB_USER"
            - name: DB_PWD
              value: "$DB_PWD"
      imagePullSecrets: # Be sure the token name matches what you created on K8s
        - name: aj-deploy